name: Publish

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - ^v?\d+\.\d+\.\d+-\w+((\.\d+)*|\.\w+(\.\d+)+)$

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Run types check
        run: npm run type-check
      - name: Run linter
        run: npm run lint
      - name: Run coverage
        run: npm run coverage
      - name: Run the packaging
        run: npm run package

  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    needs: [tests]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Configure NPM registery with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install NPM dependencies
        run: npm ci
      - name: Run the packaging
        run: npm run package
      - name: Publish to NPM
        run: npm run publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest
    needs: [tests]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Configure GPR registery with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - name: Install NPM dependencies
        run: npm ci
      - name: Run the packaging
        run: npm run package
      - name: Publish to GPR
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
